/** Farmer-facing labels — pure native script per language (no Latin mixing in UI text). */

import type { AnimalFormData } from "@/lib/ration-advisory-session";

export interface AnimalFieldLabels {
  animal: (n: number) => string;
  micHint: string;
  heard: string;
  breed: string;
  breedPh: string;
  age: string;
  agePh: string;
  stage: string;
  stageSelect: string;
  stageInMilk: string;
  stageDry: string;
  stagePregnant: string;
  stageHeifer: string;
  stageSince: string;
  stageSincePh: string;
  gaabhinCount: string;
  gaabhinPh: string;
  milk: string;
  milkPh: string;
  milkZeroNote: string;
  dailyShare: string;
  shareOfHerd: string;
  extraFeedNote: string;
  listening: string;
  stateLabel: string;
  herdPrepTitle: string;
  herdPrepSub: string;
  perAnimalTitle: string;
  seasonNote: (green: string, dry: string, season: string) => string;
}

const en: AnimalFieldLabels = {
  animal: (n) => `Animal #${n}`,
  micHint: "Tap mic — say breed, age, stage, how long in this stage, calving count, milk litres/day",
  heard: "Heard",
  breed: "Breed",
  breedPh: "e.g. Murrah, Gir",
  age: "Age (years)",
  agePh: "e.g. 5",
  stage: "Current stage",
  stageSelect: "Select…",
  stageInMilk: "Milking",
  stageDry: "Dry",
  stagePregnant: "Pregnant",
  stageHeifer: "Young / calf",
  stageSince: "In this stage since? (days / months)",
  stageSincePh: "e.g. 3 months / 60 days",
  gaabhinCount: "How many times calved / pregnant so far?",
  gaabhinPh: "e.g. 2",
  milk: "Milk (litre/day)",
  milkPh: "e.g. 8",
  milkZeroNote: "0 (dry/calf)",
  dailyShare: "Share of whole-herd ration (today)",
  shareOfHerd: "of herd total",
  extraFeedNote: "extra concentrate for this animal",
  listening: "Listening…",
  stateLabel: "Your state (for local prices & feeds)",
  herdPrepTitle: "Whole herd — prepare today",
  herdPrepSub: "Mix/prepare these amounts for all animals together (per day):",
  perAnimalTitle: "Per animal — share of the ration above",
  seasonNote: (green, dry, season) => `Season: ${season}. Green: ${green}. Dry: ${dry}. (ICAR/NDDB seasonal feeds)`,
};

const LABELS: Record<string, AnimalFieldLabels> = {
  hi: {
    animal: (n) => `पशु #${n}`,
    micHint: "माइक दबाएँ — नस्ल, उम्र, दूध/सूखी/गाभिन/बछिया, कब से, ब्यात संख्या, लीटर/दिन बोलें",
    heard: "सुना",
    breed: "नस्ल",
    breedPh: "जैसे मुर्रा, गिर",
    age: "उम्र (साल)",
    agePh: "जैसे ५",
    stage: "अभी क्या हाल",
    stageSelect: "चुनें…",
    stageInMilk: "दूध दे रही",
    stageDry: "सूखी",
    stagePregnant: "गाभिन",
    stageHeifer: "बछिया",
    stageSince: "इस अवस्था में कब से है? (दिन / महीने)",
    stageSincePh: "जैसे ३ महीने / ६० दिन",
    gaabhinCount: "अब तक कितनी बार गाभिन हुई / ब्यात हुआ?",
    gaabhinPh: "जैसे १ (पहली बार)",
    milk: "दूध (लीटर / रोज)",
    milkPh: "जैसे ५",
    milkZeroNote: "० (सूखी / बछिया)",
    dailyShare: "पूरी मंडली के राशन में इसका हिस्सा",
    shareOfHerd: "मंडली का",
    extraFeedNote: "इस पशु को अतिरिक्त दान",
    listening: "सुन रहा हूँ…",
    stateLabel: "आपका राज्य (स्थानीय दाम और चारा)",
    herdPrepTitle: "पूरी मंडली — आज तैयार करें",
    herdPrepSub: "सब पशु मिलाकर रोज इतना मिक्स करें:",
    perAnimalTitle: "हर पशु — ऊपर वाले राशन में इसका हिस्सा",
    seasonNote: (g, d, s) => `मौसम: ${s}. हरा चारा: ${g}. सूखा: ${d}. (भारतीय मौसमी चारा)`,
  },
  bn: {
    animal: (n) => `পশু #${n}`,
    micHint: "মাইক — জাত, বয়স, দুধ/শুকনো/গর্ভ/বাছুর, কবে থেকে, বাছুর সংখ্যা, লিটার/দিন বলুন",
    heard: "শোনা",
    breed: "জাত",
    breedPh: "যেমন মুরrah, গির",
    age: "বয়স (বছর)",
    agePh: "যেমন ৫",
    stage: "এখন কী অবস্থা",
    stageSelect: "বেছে নিন…",
    stageInMilk: "দুধ দিচ্ছে",
    stageDry: "শুকনো",
    stagePregnant: "গর্ভবতী",
    stageHeifer: "বাছুর",
    stageSince: "এই অবস্থায় কবে থেকে? (দিন / মাস)",
    stageSincePh: "যেমন ৩ মাস / ৬০ দিন",
    gaabhinCount: "এ পর্যন্ত কতবার গর্ভ / বাছুর?",
    gaabhinPh: "যেমন ১",
    milk: "দুধ (লিটার/দিন)",
    milkPh: "যেমন ৮",
    milkZeroNote: "০ (শুকনো/বাছুর)",
    dailyShare: "সমগ্র পালার রেশনে এই পশুর অংশ",
    shareOfHerd: "পালার",
    extraFeedNote: "অতিরিক্ত দানা",
    listening: "শুনছি…",
    stateLabel: "আপনার রাজ্য",
    herdPrepTitle: "সমগ্র পালা — আজ প্রস্তুত করুন",
    herdPrepSub: "সব পশু মিলিয়ে প্রতিদিন:",
    perAnimalTitle: "প্রতি পশু — উপরের রেশনের অংশ",
    seasonNote: (g, d, s) => `মৌসুম: ${s}. সবুজ: ${g}. শুষ্ক: ${d}.`,
  },
  ta: {
    animal: (n) => `பசு #${n}`,
    micHint: "மைக் — இனம், வயது, பால்/உலர்/கர்ப்பம்/கன்று, எப்போது முதல், கன்று எண், லிட்டர்/நாள்",
    heard: "கேட்டது",
    breed: "இனம்",
    breedPh: "முர்ரா, கிர்",
    age: "வயது (ஆண்டு)",
    agePh: "5",
    stage: "தற்போதைய நிலை",
    stageSelect: "தேர்ந்தெடு…",
    stageInMilk: "பால் கொடுக்கிறது",
    stageDry: "உலர்",
    stagePregnant: "கர்ப்பம்",
    stageHeifer: "கன்று",
    stageSince: "இந்நிலையில் எப்போது முதல்? (நாள் / மாதம்)",
    stageSincePh: "3 மாதம் / 60 நாள்",
    gaabhinCount: "இதுவரை எத்தனை முறை கர்ப்பம் / கன்று?",
    gaabhinPh: "1",
    milk: "பால் (லிட்டர்/நாள்)",
    milkPh: "8",
    milkZeroNote: "0 (உலர்/கன்று)",
    dailyShare: "முழு கூட்டத்தின் தீவனத்தில் இதன் பங்கு",
    shareOfHerd: "கூட்டத்தின்",
    extraFeedNote: "கூடுதல் தீவனம்",
    listening: "கேட்கிறேன்…",
    stateLabel: "உங்கள் மாநிலம்",
    herdPrepTitle: "முழு கூட்டம் — இன்று தயார் செய்ய",
    herdPrepSub: "அனைத்து பசுக்களுக்கும் சேர்த்து:",
    perAnimalTitle: "ஒவ்வொரு பசு — மேலுள்ள தீவனத்தில் பங்கு",
    seasonNote: (g, d, s) => `பருவம்: ${s}. பச்சை: ${g}. உலர்: ${d}.`,
  },
  te: {
    animal: (n) => `పశువు #${n}`,
    micHint: "మైక్ — జాతి, వయస్సు, పాలు/ఎండ/గర్భం/దూడ, ఎప్పటి నుంచి, లీటర్లు/రోజు",
    heard: "విన్నది",
    breed: "జాతి",
    breedPh: "ముర్రా, గిర్",
    age: "వయస్సు (సంవatsaram)",
    agePh: "5",
    stage: "ప్రస్తుత స్థితి",
    stageSelect: "ఎంచukondi…",
    stageInMilk: "పాలు ఇస్తుంది",
    stageDry: "ఎండ",
    stagePregnant: "గర్భం",
    stageHeifer: "దూడ",
    stageSince: "ఈ స్థితిలో ఎప్పటి నుంచి? (రోజులు / నెలలు)",
    stageSincePh: "3 నెలలు / 60 రోజులు",
    gaabhinCount: "ఇప్పటి వరకు ఎన్ని సార్లు గర్భం / దూడ?",
    gaabhinPh: "1",
    milk: "పాలు (లీటర్లు/రోజు)",
    milkPh: "8",
    milkZeroNote: "0 (ఎండ/దూడ)",
    dailyShare: "మొత్తం జాత్త రేషన్‌లో ఈ పశువు వాటా",
    shareOfHerd: "జాత్త",
    extraFeedNote: "అదనపు దాన",
    listening: "వినుతున్నాను…",
    stateLabel: "మీ రాష్ట్రం",
    herdPrepTitle: "మొత్తం జాత్త — ఈ రోజు తయారు చేయండి",
    herdPrepSub: "అన్ని పశువులు కలిపి రోజుకు:",
    perAnimalTitle: "ప్రతి పశువు — పై రేషన్‌లో వాటా",
    seasonNote: (g, d, s) => `ఋతువు: ${s}. పచ్చ: ${g}. ఎండ: ${d}.`,
  },
  mr: {
    animal: (n) => `पशु #${n}`,
    micHint: "माइक — जात, वय, दूध/सुकी/गर्भ/वासरू, कधीपासून, ब्यात संख्या, लिटर/दिवस",
    heard: "ऐकले",
    breed: "जात",
    breedPh: "मुरrah, गिर",
    age: "वय (वर्ष)",
    agePh: "5",
    stage: "सध्या स्थिती",
    stageSelect: "निवडा…",
    stageInMilk: "दूध देते",
    stageDry: "सुकी",
    stagePregnant: "गर्भ",
    stageHeifer: "वासरू",
    stageSince: "या अवस्थेत कधीपासून? (दिवस / महिने)",
    stageSincePh: "3 महिने / 60 दिवस",
    gaabhinCount: "आतापर्यंत किती वेळा गर्भ / वासरू?",
    gaabhinPh: "1",
    milk: "दूध (लिटर/दिवस)",
    milkPh: "8",
    milkZeroNote: "0 (सुकी/वासरू)",
    dailyShare: "संपूर्ण कळपाच्या राशनमध्ये हिस्सा",
    shareOfHerd: "कळपाचा",
    extraFeedNote: "अतिरिक्त दान",
    listening: "ऐकत आहे…",
    stateLabel: "तुमचा राज्य",
    herdPrepTitle: "संपूर्ण कळप — आज तयार करा",
    herdPrepSub: "सर्व पशु एकत्र दररोज:",
    perAnimalTitle: "प्रत्येक पशु — वरच्या राशनमध्ये हिस्सा",
    seasonNote: (g, d, s) => `ऋतू: ${s}. हिरवा: ${g}. sukha: ${d}.`,
  },
  gu: {
    animal: (n) => `પશુ #${n}`,
    micHint: "માઇક — જાત, ઉંમર, દૂધ/સૂકી/ગર્ભ/વાછરડું, ક્યારથી, વાછરડાંની સંખ્યા, લિટર/દિવસ",
    heard: "સાંભળ્યું",
    breed: "જાત",
    breedPh: "મુર્રા, ગir",
    age: "ઉંમર (વર્ષ)",
    agePh: "5",
    stage: "હાલની સ્થિતિ",
    stageSelect: "પસંદ કરો…",
    stageInMilk: "દૂધ આપે",
    stageDry: "સૂકી",
    stagePregnant: "ગર્ભ",
    stageHeifer: "વાછરડું",
    stageSince: "આ સ્થિતિમાં ક્યારથી? (દિવસ / મહિના)",
    stageSincePh: "3 મહિના / 60 દિવસ",
    gaabhinCount: "હજી સudhi કેટલી વાર ગર્ભ / વાછરડું?",
    gaabhinPh: "1",
    milk: "દૂધ (લિટર/દિવસ)",
    milkPh: "8",
    milkZeroNote: "0 (સૂકી/વાછરડું)",
    dailyShare: "આખી મંડળીના રાશનમાં ભાગ",
    shareOfHerd: "મંડળીના",
    extraFeedNote: "વધારાનું દાન",
    listening: "સાંભળu chu…",
    stateLabel: "તમારo રાજ્ય",
    herdPrepTitle: "આખી મંડળી — આજે તૈયાર કરો",
    herdPrepSub: "બધા પશu એક કરીને દરરોજ:",
    perAnimalTitle: "દરેક પશu — ઉપરના રાશનનો ભાગ",
    seasonNote: (g, d, s) => `ઋતu: ${s}. હirvo: ${g}. sukho: ${d}.`,
  },
  kn: {
    animal: (n) => `ಪಶು #${n}`,
    micHint: "ಮೈಕ್ — breed, vayassu, halu/sukhi/garbha/kuzhi, yavaga inda, litre",
    heard: "ಕೇಳಿದ್ದು",
    breed: "jati",
    breedPh: "Murrah",
    age: "vayassu (varsha)",
    agePh: "5",
    stage: "iga sthiti",
    stageSelect: "aayke maadi…",
    stageInMilk: "halu kodutade",
    stageDry: "sukhi (ondu)",
    stagePregnant: "garbha",
    stageHeifer: "kuzhi",
    stageSince: "ee sthiti yavaga inda? (dina / tingalu)",
    stageSincePh: "3 tingalu / 60 dina",
    gaabhinCount: "ivarege eshtu sala garbha / huvudu?",
    gaabhinPh: "1",
    milk: "halu (litre/dina)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/kuzhi)",
    dailyShare: "elaa jothe ration alli ee pashuvina bhaga",
    shareOfHerd: "jothe",
    extraFeedNote: "extra dan",
    listening: "kelutteeni…",
    stateLabel: "nimma rajya",
    herdPrepTitle: "Elaa jothe — ivattu tayarisi",
    herdPrepSub: "Ella pashugalannu serisi dina:",
    perAnimalTitle: "Prati pashuvu — mele ration nalli bhaga",
    seasonNote: (g, d, s) => `Ritu: ${s}. Hasiru: ${g}. Ona: ${d}.`,
  },
  ml: {
    animal: (n) => `പശu #${n}`,
    micHint: "മൈക്ക് — breed, vayassu, paal/sukhi/garbham/kuzhi, eppol muthal, litre",
    heard: "കേട്ടത്",
    breed: "jati",
    breedPh: "Murrah",
    age: "vayassu (varsham)",
    agePh: "5",
    stage: "ippol sthiti",
    stageSelect: "theranju edukkuka…",
    stageInMilk: "paal tharunnu",
    stageDry: "sukhi",
    stagePregnant: "garbham",
    stageHeifer: "kuzhi",
    stageSince: "ee avasthayil eppol muthal? (divasam / masam)",
    stageSincePh: "3 masam / 60 divasam",
    gaabhinCount: "ippol vare etra thavana garbham / kuzhi?",
    gaabhinPh: "1",
    milk: "paal (litre/day)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/kuzhi)",
    dailyShare: "mottam koottathinte ration-il bhagam",
    shareOfHerd: "koottathinte",
    extraFeedNote: "extra danam",
    listening: "kelkkunnu…",
    stateLabel: "nningalude rajyam",
    herdPrepTitle: "Mottam koottam — innu thayyarakkuka",
    herdPrepSub: "Ellaa pashukkalum kootti daily:",
    perAnimalTitle: "Oro pashuvum — mukalil ulla ration-il bhagam",
    seasonNote: (g, d, s) => `Ritu: ${s}. Pacha: ${g}. Ona: ${d}.`,
  },
  pa: {
    animal: (n) => `ਪਸ਼u #${n}`,
    micHint: "ਮਾਈਕ — ਨasl, ਉਮਰ, ਦੂਧ/ਸukhi/ਗਰਭ/ਬacchiya, ਕab ਤੋਂ, ਲੀਟਰ/ਦਿਨ ਬੋਲੋ",
    heard: "ਸੁਣਿਆ",
    breed: "ਨasl",
    breedPh: "ਮੁਰrah, ਗir",
    age: "ਉਮਰ (ਸਾਲ)",
    agePh: "5",
    stage: "ਹੁਣ ਕੀ ਹਾਲat",
    stageSelect: "ਚੁਣੋ…",
    stageInMilk: "ਦੂਧ ਦਿੰਦੀ",
    stageDry: "ਸukhi",
    stagePregnant: "ਗਰਭ",
    stageHeifer: "ਬacchiya",
    stageSince: "ਇਸ ਹਾਲat ਵਿੱਚ ਕab ਤੋਂ? (ਦਿਨ / ਮਹੀne)",
    stageSincePh: "3 ਮਹੀne / 60 ਦਿਨ",
    gaabhinCount: "ਹੁਣ ਤੱਕ ਕਿੰਨੀ ਵਾਰ ਗਰਭ / ਬacchiya?",
    gaabhinPh: "1",
    milk: "ਦੂਧ (ਲੀਟਰ/ਦਿਨ)",
    milkPh: "8",
    milkZeroNote: "0 (ਸukhi/ਬacchiya)",
    dailyShare: "ਪੂਰੀ ਮੰਡਲੀ ਦੇ ਰਾਸ਼ਨ ਵਿੱਚ ਹਿੱਸਾ",
    shareOfHerd: "ਮੰਡਲੀ ਦੇ",
    extraFeedNote: "ਵਧੀਕ ਦਾਨ",
    listening: "ਸੁਣ ਰaha ਹaan…",
    stateLabel: "ਤੁਹਾਡਾ ਰਾਜ",
    herdPrepTitle: "ਪੂਰੀ ਮੰਡਲੀ — ਅaj ਤਿਆਰ ਕਰੋ",
    herdPrepSub: "ਸਾਰੇ ਪਸ਼u ਮਿਲਾ ਕੇ ਰੋਜ਼:",
    perAnimalTitle: "ਹਰ ਪਸ਼u — ਉੱਪਰ ਵਾਲੇ ਰਾਸ਼ਨ ਦਾ ਹਿੱਸਾ",
    seasonNote: (g, d, s) => `ਮausam: ${s}. ਹara: ${g}. ਸukha: ${d}.`,
  },
  or: {
    animal: (n) => `ପଶu #${n}`,
    micHint: "mic — breed, baya, dudha/sukhi/garbha/bachha, kebe tharu, litre",
    heard: "ଶୁଣili",
    breed: "jati",
    breedPh: "Murrah",
    age: "baya (barsha)",
    agePh: "5",
    stage: "ebe sthiti",
    stageSelect: "banchantu…",
    stageInMilk: "dudha deuchi",
    stageDry: "sukhi",
    stagePregnant: "garbha",
    stageHeifer: "bachha",
    stageSince: "ei sthiti re kebe tharu? (dina / masa)",
    stageSincePh: "3 masa / 60 dina",
    gaabhinCount: "ebe jae kete thara garbha / bachha hela?",
    gaabhinPh: "1",
    milk: "dudha (litre/dina)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/bachha)",
    dailyShare: "sampurna mandali ration re ansha",
    shareOfHerd: "mandali",
    extraFeedNote: "extra dan",
    listening: "suni rahi…",
    stateLabel: "apananka rajya",
    herdPrepTitle: "Sampurna mandali — aji tayari",
    herdPrepSub: "Saba pashu mili dina:",
    perAnimalTitle: "Prati pashu — upare ration re ansha",
    seasonNote: (g, d, s) => `Rutu: ${s}. Sabuja: ${g}. Sukha: ${d}.`,
  },
  as: {
    animal: (n) => `পশu #${n}`,
    micHint: "mic — breed, boi, gakh/sukhi/garbhini/bachha, kiman din thaki, litre",
    heard: "শুনা",
    breed: "jati",
    breedPh: "Murrah",
    age: "boi (bosor)",
    agePh: "5",
    stage: "etiya obostha",
    stageSelect: "bachilo…",
    stageInMilk: "gakh dibe",
    stageDry: "sukhi",
    stagePregnant: "garbhini",
    stageHeifer: "bachha",
    stageSince: "ei obosthay kiman din thaki? (din / mah)",
    stageSincePh: "3 mah / 60 din",
    gaabhinCount: "etiya loi kiman bar garbhini / bachha?",
    gaabhinPh: "1",
    milk: "gakh (litre/din)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/bachha)",
    dailyShare: "sampurna pAlor ration ot bhag",
    shareOfHerd: "pAlor",
    extraFeedNote: "extra dan",
    listening: "shunisu…",
    stateLabel: "apunar rajya",
    herdPrepTitle: "Sampurna pal — aji prastut karo",
    herdPrepSub: "Sob pashu mile dina:",
    perAnimalTitle: "Prati pashu — uporor ration ot bhag",
    seasonNote: (g, d, s) => `Ritu: ${s}. Sabuj: ${g}. Sukhi: ${d}.`,
  },
  ur: {
    animal: (n) => `پशu #${n}`,
    micHint: "mic — nasl, umar, doodh/sukhi/hamla/bachha, kab se, litre",
    heard: "Suna",
    breed: "nasl",
    breedPh: "Murrah",
    age: "umar (saal)",
    agePh: "5",
    stage: "ab halat",
    stageSelect: "Chuniye…",
    stageInMilk: "doodh deti",
    stageDry: "sukhi",
    stagePregnant: "hamla",
    stageHeifer: "bachha",
    stageSince: "is halat mein kab se? (din / mahine)",
    stageSincePh: "3 mahine / 60 din",
    gaabhinCount: "ab tak kitni baar hamla / bachha hua?",
    gaabhinPh: "1",
    milk: "doodh (litre/din)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/bachha)",
    dailyShare: "pure mandli ke ration mein hissa",
    shareOfHerd: "mandli ke",
    extraFeedNote: "extra dan",
    listening: "Sun raha hoon…",
    stateLabel: "aapka sooba",
    herdPrepTitle: "Poori mandli — aaj tayyar karein",
    herdPrepSub: "Tamam pashu mila kar roz:",
    perAnimalTitle: "Har pashu — upar wale ration ka hissa",
    seasonNote: (g, d, s) => `Mausam: ${s}. Hara: ${g}. Sukha: ${d}.`,
  },
  en,
};

export function getAnimalFieldLabels(lang: string | null | undefined): AnimalFieldLabels {
  return LABELS[lang ?? ""] ?? en;
}

export function localizedStatusLabel(status: AnimalFormData["status"], lang: string | null | undefined): string {
  const L = getAnimalFieldLabels(lang);
  switch (status) {
    case "in_milk": return L.stageInMilk;
    case "dry": return L.stageDry;
    case "pregnant": return L.stagePregnant;
    case "heifer": return L.stageHeifer;
    default: return "—";
  }
}

export function seasonLabelLocalized(season: "kharif" | "rabi" | "summer", lang: string | null): string {
  const map: Record<string, Record<string, string>> = {
    hi: {
      kharif: "खरीफ (बारिश के बाद)",
      rabi: "रabi (सर्दी — बersim)",
      summer: "गarmi (नेपier/भूसा)",
    },
    bn: { kharif: "খরif", rabi: "রabi", summer: "গrishmo" },
    ta: { kharif: "கharif", rabi: "ரabi", summer: "கோடை" },
    te: { kharif: "ఖharif", rabi: "రabi", summer: "వSummer" },
    mr: { kharif: "खarif", rabi: "रabi", summer: "उnhaala" },
    gu: { kharif: "ખarif", rabi: "રabi", summer: "ઉnhaalo" },
    kn: { kharif: "ಖharif", rabi: "ರabi", summer: "ಬSummer" },
    ml: { kharif: "ഖharif", rabi: "റabi", summer: "വSummer" },
    pa: { kharif: "ਖharif", rabi: "ਰabi", summer: "ਗrishm" },
    or: { kharif: "ଖharif", rabi: "ରabi", summer: "ଗrishma" },
    as: { kharif: "খharif", rabi: "ৰabi", summer: "গrishm" },
    ur: { kharif: "خريف", rabi: "ربيع", summer: "گرmi" },
    en: { kharif: "Kharif (monsoon)", rabi: "Rabi (winter)", summer: "Summer" },
  };
  const L = map[lang ?? ""] ?? map.en;
  return L[season];
}
