/** Farmer-facing field labels for Ration Advisory animal blocks — all 12 languages + English. */

import type { AnimalFormData } from "@/lib/ration-advisory-session";

export interface AnimalFieldLabels {
  animal: (n: number) => string;
  micHint: string;
  heard: string;
  breed: string;
  breedPh: string;
  age: string;
  agePh: string;
  stage: string;
  stageSelect: string;
  stageInMilk: string;
  stageDry: string;
  stagePregnant: string;
  stageHeifer: string;
  gaabhinCount: string;
  gaabhinPh: string;
  milk: string;
  milkPh: string;
  milkZeroNote: string;
  dailyShare: string;
  listening: string;
}

const en: AnimalFieldLabels = {
  animal: (n) => `Animal #${n}`,
  micHint: "Tap mic — say breed, age, milk/dry/pregnant, how many times calved/pregnant, litres/day",
  heard: "Heard",
  breed: "Breed",
  breedPh: "e.g. Murrah, Gir",
  age: "Age (years)",
  agePh: "e.g. 5",
  stage: "Now — milking / dry / pregnant / young",
  stageSelect: "Select…",
  stageInMilk: "Giving milk",
  stageDry: "Dry (not milking)",
  stagePregnant: "Pregnant",
  stageHeifer: "Young / calf (not milking)",
  gaabhinCount: "How many times calved / pregnant so far?",
  gaabhinPh: "e.g. 2",
  milk: "Milk (litre/day)",
  milkPh: "e.g. 8",
  milkZeroNote: "0 (dry/calf)",
  dailyShare: "Daily share from herd ration",
  listening: "Listening…",
};

const LABELS: Record<string, AnimalFieldLabels> = {
  hi: {
    animal: (n) => `पशu #${n}`,
    micHint: "माइक दबाएँ — nasl, umar (5 saal ki hai), doodh/sukhi/garbh, kitni baar gaabhin, roz kitna litre",
    heard: "सुना",
    breed: "नस्ल",
    breedPh: "जैसे Murrah, Gir",
    age: "उम्र (saal)",
    agePh: "जैसे 5",
    stage: "अभी — doodh / sukhi / garbh / bachiya",
    stageSelect: "चुनें…",
    stageInMilk: "दूध दे रही (doodh)",
    stageDry: "सूखी (doodh nahi)",
    stagePregnant: "गाभिन / garbh",
    stageHeifer: "बच्ची / bachiya (doodh nahi)",
    gaabhinCount: "अब तक kitni baar gaabhin hui / bachha hua?",
    gaabhinPh: "जैसे 1 (pehli baar)",
    milk: "Doodh (litre / roz)",
    milkPh: "जैसे 5",
    milkZeroNote: "0 (sukhi/bachiya)",
    dailyShare: "Mandli ke ration mein iska hissa (roz)",
    listening: "सुन रaha hoon…",
  },
  bn: {
    animal: (n) => `পশu #${n}`,
    micHint: "মাইক — জাত, বয়স, দুধ/শুকনো/গর্ভ, কতবার গর্ভ/বাছুর, লিটার/দিন",
    heard: "শোনা",
    breed: "জাত",
    breedPh: "যেমন Murrah",
    age: "বয়স (বছর)",
    agePh: "যেমন 5",
    stage: "এখন — দুধ / শুকনো / গর্ভ / বাছুর",
    stageSelect: "বেছে নিন…",
    stageInMilk: "দুধ দিচ্ছে",
    stageDry: "শুকনো",
    stagePregnant: "গর্ভবতী",
    stageHeifer: "বাছুর / তরুণ",
    gaabhinCount: "এ পর্যন্ত কতবার গর্ভ / বাছুর?",
    gaabhinPh: "যেমন 1",
    milk: "দুধ (লিটার/দিন)",
    milkPh: "যেমন 8",
    milkZeroNote: "0 (শুকনো/বাছুর)",
    dailyShare: "দৈনিক রেশনের অংশ",
    listening: "শুনছি…",
  },
  ta: {
    animal: (n) => `மிருகம் #${n}`,
    micHint: "மைக் — இனம், வயது, பால்/dry/கர்ப்பம், எத்தனை முறை, லிட்டர்/நாள்",
    heard: "கேட்டது",
    breed: "இனம்",
    breedPh: "Murrah, Gir",
    age: "வயது (ஆண்டு)",
    agePh: "5",
    stage: "இப்போது — பால் / dry / கர்ப்பம் / கன்று",
    stageSelect: "தேர்ந்தெடு…",
    stageInMilk: "பால் கொடுக்கிறது",
    stageDry: "உலர்ந்த (dry)",
    stagePregnant: "கர்ப்பம்",
    stageHeifer: "இளம் / கன்று",
    gaabhinCount: "இதுவரை எத்தனை முறை கர்ப்பம் / கன்று?",
    gaabhinPh: "1",
    milk: "பால் (லிட்டர்/நாள்)",
    milkPh: "8",
    milkZeroNote: "0 (dry/கன்று)",
    dailyShare: "தினசரி பங்கு",
    listening: "கேட்கிறேன்…",
  },
  te: {
    animal: (n) => `పశuvu #${n}`,
    micHint: "మైక్ — breed, vayassu, paalu/dry/garbham, enni saarlu, litre/roju",
    heard: "విన్నది",
    breed: "Breed / jati",
    breedPh: "Murrah",
    age: "Vayassu (samvatsaram)",
    agePh: "5",
    stage: "Ippudu — paalu / dry / garbham / bachha",
    stageSelect: "Emiriyandi…",
    stageInMilk: "Paalu istundi",
    stageDry: "Dry (paalu ledu)",
    stagePregnant: "Garbham",
    stageHeifer: "Bachha / young",
    gaabhinCount: "Ippati varaku enni saarlu garbham / dhenu?",
    gaabhinPh: "1",
    milk: "Paalu (litre/roju)",
    milkPh: "8",
    milkZeroNote: "0 (dry/bachha)",
    dailyShare: "Rojuva rasyon bhagam",
    listening: "Vinatunna…",
  },
  mr: {
    animal: (n) => `पशu #${n}`,
    micHint: "माइक — nasl, vay, dudh/sukhi/garbh, kiti vela, litre/divas",
    heard: "ऐकले",
    breed: "Nasl",
    breedPh: "Murrah",
    age: "Vay (varsha)",
    agePh: "5",
    stage: "Aata — dudh / sukhi / garbha / bachha",
    stageSelect: "Nivda…",
    stageInMilk: "Dudh dete",
    stageDry: "Sukhi",
    stagePregnant: "Garbha",
    stageHeifer: "Bachha / tarun",
    gaabhinCount: "Abhyat kiti vela garbha / vasa zala?",
    gaabhinPh: "1",
    milk: "Dudh (litre/divas)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/bachha)",
    dailyShare: "Dainik rasyon bhag",
    listening: "Aikat aahe…",
  },
  gu: {
    animal: (n) => `પશu #${n}`,
    micHint: "માઇક — nasl, umar, dudh/sukhi/garbh, ketli vaar, litre/din",
    heard: "સાંભળ્યું",
    breed: "Nasl",
    breedPh: "Murrah",
    age: "Umar (varsh)",
    agePh: "5",
    stage: "Have — dudh / sukhi / garbh / bachhu",
    stageSelect: "Pasand karo…",
    stageInMilk: "Dudh aape",
    stageDry: "Sukhi",
    stagePregnant: "Garbh",
    stageHeifer: "Bachhu / young",
    gaabhinCount: "Sudhi ketli vaar garbh / bachhu thayu?",
    gaabhinPh: "1",
    milk: "Dudh (litre/din)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/bachhu)",
    dailyShare: "Dainik rasyon bhag",
    listening: "Sambhḷu chu…",
  },
  kn: {
    animal: (n) => `ಪಶu #${n}`,
    micHint: "ಮೈಕ್ — breed, vayassu, halu/dry/garbha, eshtu sala, litre/dina",
    heard: "ಕೇಳಿದ್ದು",
    breed: "Breed",
    breedPh: "Murrah",
    age: "Vayassu (varsha)",
    agePh: "5",
    stage: "Iga — halu / dry / garbha / kuzhi",
    stageSelect: "Aayke maadi…",
    stageInMilk: "Halu kodutade",
    stageDry: "Dry",
    stagePregnant: "Garbha",
    stageHeifer: "Kuzhi / young",
    gaabhinCount: "Ivarege eshtu sala garbha / huvudu?",
    gaabhinPh: "1",
    milk: "Halu (litre/dina)",
    milkPh: "8",
    milkZeroNote: "0 (dry/kuzhi)",
    dailyShare: "Dina rasyon bhaga",
    listening: "Kelutteeni…",
  },
  ml: {
    animal: (n) => `പശu #${n}`,
    micHint: "മൈക്ക് — breed, vayassu, paal/dry/garbham, etra thavana, litre/day",
    heard: "കേട്ടത്",
    breed: "Breed",
    breedPh: "Murrah",
    age: "Vayassu (varsham)",
    agePh: "5",
    stage: "Ippol — paal / dry / garbham / kuzhi",
    stageSelect: "Theranju edukkuka…",
    stageInMilk: "Paal tharunnu",
    stageDry: "Dry",
    stagePregnant: "Garbham",
    stageHeifer: "Kuzhi / young",
    gaabhinCount: "Ippol vare etra thavana garbham / kuzhi?",
    gaabhinPh: "1",
    milk: "Paal (litre/day)",
    milkPh: "8",
    milkZeroNote: "0 (dry/kuzhi)",
    dailyShare: "Dina rasyon bhagam",
    listening: "Kelkkunnu…",
  },
  pa: {
    animal: (n) => `ਪਸ਼u #${n}`,
    micHint: "ਮਾਈਕ — nasl, umar, doodh/sukhi/garbh, kinni vaar, litre/din",
    heard: "ਸੁਣਿਆ",
    breed: "Nasl",
    breedPh: "Murrah",
    age: "Umar (saal)",
    agePh: "5",
    stage: "Hunn — doodh / sukhi / garbhi / bachha",
    stageSelect: "Chuno…",
    stageInMilk: "Doodh dindi",
    stageDry: "Sukhi",
    stagePregnant: "Garbhi",
    stageHeifer: "Bachha / young",
    gaabhinCount: "Hun tak kinni vaar garbhi / bachha hoya?",
    gaabhinPh: "1",
    milk: "Doodh (litre/din)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/bachha)",
    dailyShare: "Roz rasyon hissa",
    listening: "Sun raha haan…",
  },
  or: {
    animal: (n) => `ପଶu #${n}`,
    micHint: "ମାଇକ — breed, baya, dudha/dry/garbha, kete thara, litre/dina",
    heard: "ଶୁଣିଲି",
    breed: "Breed",
    breedPh: "Murrah",
    age: "Baya (barsha)",
    agePh: "5",
    stage: "Ebe — dudha / dry / garbha / bachha",
    stageSelect: "Banchantu…",
    stageInMilk: "Dudha deuchi",
    stageDry: "Dry",
    stagePregnant: "Garbha",
    stageHeifer: "Bachha / young",
    gaabhinCount: "Ebe jae kete thara garbha / bachha hela?",
    gaabhinPh: "1",
    milk: "Dudha (litre/dina)",
    milkPh: "8",
    milkZeroNote: "0 (dry/bachha)",
    dailyShare: "Dainika rasyon ansha",
    listening: "Suni rahi…",
  },
  as: {
    animal: (n) => `পশu #${n}`,
    micHint: "মাইক — breed, boi, gakh/dry/garbhini, kiman bar, litre/din",
    heard: "শুনা",
    breed: "Breed",
    breedPh: "Murrah",
    age: "Boi (bosor)",
    agePh: "5",
    stage: "Etiya — gakh / dry / garbhini / bachha",
    stageSelect: "Bachilo…",
    stageInMilk: "Gakh dibe",
    stageDry: "Dry",
    stagePregnant: "Garbhini",
    stageHeifer: "Bachha / young",
    gaabhinCount: "Etiya loi kiman bar garbhini / bachha?",
    gaabhinPh: "1",
    milk: "Gakh (litre/din)",
    milkPh: "8",
    milkZeroNote: "0 (dry/bachha)",
    dailyShare: "Dainik rasyon ansha",
    listening: "Shunisu…",
  },
  ur: {
    animal: (n) => `پशu #${n}`,
    micHint: "مائیک — nasl, umar, doodh/sukhi/hamla, kitni baar, litre/din",
    heard: "Suna",
    breed: "Nasl",
    breedPh: "Murrah",
    age: "Umar (saal)",
    agePh: "5",
    stage: "Ab — doodh / sukhi / hamla / bachha",
    stageSelect: "Chuniye…",
    stageInMilk: "Doodh deti",
    stageDry: "Sukhi",
    stagePregnant: "Hamla / garbh",
    stageHeifer: "Bachha / young",
    gaabhinCount: "Ab tak kitni baar hamla / bachha hua?",
    gaabhinPh: "1",
    milk: "Doodh (litre/din)",
    milkPh: "8",
    milkZeroNote: "0 (sukhi/bachha)",
    dailyShare: "Roz ration hissa",
    listening: "Sun raha hoon…",
  },
  en,
};

export function getAnimalFieldLabels(lang: string | null | undefined): AnimalFieldLabels {
  return LABELS[lang ?? ""] ?? en;
}

export function localizedStatusLabel(status: AnimalFormData["status"], lang: string | null | undefined): string {
  const L = getAnimalFieldLabels(lang);
  switch (status) {
    case "in_milk": return L.stageInMilk;
    case "dry": return L.stageDry;
    case "pregnant": return L.stagePregnant;
    case "heifer": return L.stageHeifer;
    default: return "—";
  }
}
